baseURL = 'https://example.org/'
languageCode = 'en-uk'
title = 'cole theme'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Projects'
pageRef = '/projects'
weight = 20

[[menus.main]]
name = 'Blog'
pageRef = '/blog'
weight = 20

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
