name = 'cole'
license = 'MIT'
licenselink = 'https://github.com/owner/repo/LICENSE'
description = 'Personal theme for my site'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/c-mansfield/c-mansfield.github.io'

# If the theme has a single author
[author]
  name = 'Cole Mansfield'
  homepage = 'Cole'