languageCode = 'en-uk'
title = 'Cole Mansfield'
theme = "cole"
baseURL = ""
relativeURLs = "True"

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
            hardWraps = true

[params]
    themeStyle = "auto"
    favicon = "/img/favicon.png"
    fadeIn = false
    showMenu = false