name: Build Docker Image and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Initial setup
        run: mkdir app
      - name: Build Docker image
        run: |
          docker build . --file Dockerfile --tag my-site
          docker cp $(docker create my-site):/usr/share/nginx/html/. app
      - name: Upload Site To Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: app
          retention-days: 1
          if-no-files-found: warn
  deploy:
    concurrency: ci-${{ github.ref }}
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy site to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1