name: Build Docker Image and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build Docker image
        run: |
          docker build . --file Dockerfile --tag my-site
      - uses: shrink/actions-docker-extract@v1
        id: extract
        with:
          image: 'my-site'
          path: 'usr/share/nginx/html/.'
      - name: Upload site to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: github-pages
          path: ${{ steps.extract.outputs.destination }}
          retention-days: 1
          if-no-files-found: warn
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy site to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1